version: "3"
services:
  node-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - env=dev
    ports:
      - "8088:80"
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules